import { ChangeDetectorRef, Component, OnInit, ViewChild } from '@angular/core';
import { FormControl, Validators } from '@angular/forms';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';
import { AlertService } from 'app/services/alert.service';

@Component({
    selector: 'app-ingresos',
    templateUrl: './ingresos.component.html',
    styleUrls: ['./ingresos.component.scss'],
})
export class IngresosComponent implements OnInit {
    isLoading: boolean = false;
    mampuesto$: MatTableDataSource<any>;
    displayedColumnsMampuesto: string[] = [
        'cliente',
        'observaciones',
        'avisoCliente',
        'revisado',
        'estado',
        'guia',
        'factura',
        'ubicacion',
        'proyecto',
        'fecha',
        'observaciones1',
        'oneducto',
        'cajetin',
        'twoductos',
        'mixto',
        'tresductos',
        'maestra',
        'doce',
        'veinte',
        'groutnivelacion',
        'groutestandar',
        'groutplus',
        'sealestandar',
        'sealplus',
        'finish',
        'deko',
        'protector',
        'dintel',
        'peso',
        'totalPalets',
        'totalMorteros',
        'transporte'
    ];
    @ViewChild('_paginator') _paginator: MatPaginator;
    @ViewChild(MatSort) _sort: MatSort;

    constructor(
        private routerService: Router,
        private readonly alertService: AlertService,
        private _changeDetectorRef: ChangeDetectorRef
    ) {}

    ngOnInit() {
        let ingre = [];
        ingre = [
            {
            cliente: 'Tecniurban',
            observaciones: '',
            avisoCliente: '',
            revisado: '',
            estado: 'Confirmado',
            guia: '',
            factura: '',
            ubicacion: 'Conocoto',
            proyecto: 'Valle Real',
            fecha: 'Martes, 2 Abril',
            observaciones1: '',
            oneducto: '',
            cajetin: '',
            twoductos: '',
            mixto: '',
            tresductos: '',
            maestra: '',
            doce: '',
            veinte: '',
            groutnivelacion: '',
            groutestandar: '',
            groutplus: '',
            sealestandar: 200,
            sealplus: '',
            finish: '',
            deko: '',
            protector: '',
            dintel: '',
            peso: 5,
            totalPalets: '',
            totalMorteros: 4,
            transporte: 'Camion'
        },
            {
                cliente: 'Ing Luis Benavides',
                observaciones: 'Bloque',
                avisoCliente: '',
                revisado: 'Diego Haro',
                estado: 'Confirmado',
                guia: '',
                factura: '',
                ubicacion: 'Machala',
                proyecto: 'UVC General Serrano',
                fecha: 'Martes, 2 Abril',
                observaciones1: 'Trailer propio',
                oneducto: '',
                cajetin: '',
                twoductos: '',
                mixto: '',
                tresductos: 14,
                maestra: '',
                doce: '',
                veinte: 113.26,
                groutnivelacion: '',
                groutestandar: '',
                groutplus: 180,
                sealestandar: 200,
                sealplus: '',
                finish: '',
                deko: '',
                protector: '',
                dintel: '',
                peso: 33.69,
                totalPalets: '',
                totalMorteros: 4,
                transporte: 'Camion'
            },

            {
                cliente: 'Consorcio Seguridad',
                observaciones: 'Bloque',
                avisoCliente: '',
                revisado: '',
                estado: 'Confirmado',
                guia: '',
                factura: '',
                ubicacion: 'Quevedo',
                proyecto: 'Upc 7 de Octubre',
                fecha: 'Miercoles, 3 Abril',
                observaciones1: '',
                oneducto: '',
                cajetin: '',
                twoductos: '',
                mixto: '',
                tresductos: 10,
                maestra: '',
                doce: '80.90',
                veinte: '',
                groutnivelacion: '',
                groutestandar: 120,
                groutplus: '',
                sealestandar: '',
                sealplus: '',
                finish: '',
                deko: '',
                protector: '',
                dintel: '',
                peso: 20.28,
                totalPalets: 10,
                totalMorteros: 2,
                transporte: 'Mula'
            }, {
                cliente: 'Ing Luis Benavides',
                observaciones: 'Bloque',
                avisoCliente: '',
                revisado: 'Diego Haro',
                estado: 'Confirmado',
                guia: '',
                factura: '',
                ubicacion: 'Machala',
                proyecto: 'UVC General Serrano',
                fecha: 'Miercoles, 3 Abril',
                observaciones1: 'Trailer propio',
                oneducto: '',
                cajetin: '',
                twoductos: '',
                mixto: '',
                tresductos: 15,
                maestra: '',
                doce: '',
                veinte: 121.35,
                groutnivelacion: '',
                groutestandar: '',
                groutplus: 180,
                sealestandar: '',
                sealplus: '',
                finish: '',
                deko: '',
                protector: '',
                dintel: '',
                peso: 30.42,
                totalPalets: 15,
                totalMorteros: 3,
                transporte: 'Trailer'
            }, {
                cliente: 'Mayorga Francisco',
                observaciones: 'Bloque',
                avisoCliente: '',
                revisado: 'Diego Haro',
                estado: 'Confirmar Pago',
                guia: '',
                factura: '',
                ubicacion: 'Cumbaya',
                proyecto: 'MABEC2',
                fecha: 'Miercoles, 3 Abril',
                observaciones1: 'Trailer propio',
                oneducto: '',
                cajetin: '',
                twoductos: '',
                mixto: '',
                tresductos: '',
                maestra: '',
                doce: '',
                veinte: '',
                groutnivelacion: '',
                groutestandar: '',
                groutplus: '',
                sealestandar: 200,
                sealplus: '',
                finish: '',
                deko: '',
                protector: '',
                dintel: '',
                peso: 5,
                totalPalets: '',
                totalMorteros: 4,
                transporte: 'Mula'
            },
            {
                cliente: 'Ing Santiago Padilla',
                observaciones: '',
                avisoCliente: '',
                revisado: '',
                estado: 'Confirmadar Pago',
                guia: '',
                factura: '',
                ubicacion: 'Ambato',
                proyecto: 'Residencia Montalvo',
                fecha: 'Miercoles, 3 Abril',
                observaciones1: '',
                oneducto: '',
                cajetin: '',
                twoductos: '',
                mixto: '',
                tresductos: 8,
                maestra: '',
                doce: 60.68,
                veinte: '',
                groutnivelacion: '',
                groutestandar: 80,
                groutplus: '',
                sealestandar: 20,
                sealplus: '',
                finish: '',
                deko: '',
                protector: '',
                dintel: '',
                peso: 15.51,
                totalPalets: 8,
                totalMorteros: 2,
                transporte: 'Camion'
            },
            {
                cliente: 'Constructora Cufig',
                observaciones: '',
                avisoCliente: '',
                revisado: 'Diego Haro',
                estado: 'Confirmado',
                guia: '',
                factura: '',
                ubicacion: 'Esmeraldas',
                proyecto: 'UPC Montalvo',
                fecha: 'Miercoles, 3 Abril',
                observaciones1: '',
                oneducto: '',
                cajetin: '',
                twoductos: '',
                mixto: 4,
                tresductos: 11,
                maestra: '',
                doce: 121.35,
                veinte: '',
                groutnivelacion: 30,
                groutestandar: 180,
                groutplus: '',
                sealestandar: 90,
                sealplus: '',
                finish: '',
                deko: '',
                protector: '',
                dintel: '',
                peso: 31.17,
                totalPalets: 15,
                totalMorteros: 4,
                transporte: 'Mula'
            },
            {
                cliente: 'Londoño Constructores',
                observaciones: '',
                avisoCliente: '',
                revisado: ' ',
                estado: 'Confirmado',
                guia: '',
                factura: '',
                ubicacion: 'Puembo',
                proyecto: 'Proaño Siguencia',
                fecha: 'Miercoles, 3 Abril',
                observaciones1: '',
                oneducto: '',
                cajetin: '',
                twoductos: 1,
                mixto: '',
                tresductos: 9,
                maestra: 432,
                doce: 80.90,
                veinte: '',
                groutnivelacion: 30,
                groutestandar: '',
                groutplus: 120,
                sealestandar: '',
                sealplus: '',
                finish: '',
                deko: '',
                protector: '',
                dintel: '',
                peso: 21.03,
                totalPalets: 10,
                totalMorteros: 3,
                transporte: 'Mula'
            },
            {
                cliente: 'Consorcio Seguridad',
                observaciones: '',
                avisoCliente: '',
                revisado: 'Diego Haro',
                estado: 'Confirmado',
                guia: '',
                factura: '',
                ubicacion: 'Buena Fe',
                proyecto: 'UPC Buena Fe',
                fecha: 'Miercoles, 3 Abril',
                observaciones1: '',
                oneducto: '',
                cajetin: '',
                twoductos: '',
                mixto: '',
                tresductos: '',
                maestra: '',
                doce: '',
                veinte: '',
                groutnivelacion: '',
                groutestandar: '',
                groutplus: '',
                sealestandar: 90,
                sealplus: '',
                finish: '',
                deko: '',
                protector: '',
                dintel: '',
                peso: 2.25,
                totalPalets: '',
                totalMorteros: 2,
                transporte: 'Mula'
            },
        ]
        this.mampuesto$ = new MatTableDataSource(ingre);
        this.mampuesto$.paginator = this._paginator;
        this.mampuesto$.sort = this._sort;
        this._changeDetectorRef.markForCheck();
    }
}
